import { useEffect, useState } from "react";
import type { SeatingHistoryRow, StudentExperienceRow } from "../../application/seating-history-service";
import type { SeatingAssignment } from "../../domain/models";
import { HistoricalImportPreview } from "./historical-import-preview";

type SemesterFilter = "all" | 1 | 2;

export function SeatingHistory({ schoolYearId, onBack, onOpenChart }: { schoolYearId: string; onBack: () => void; onOpenChart: (assignments: SeatingAssignment[]) => void }): JSX.Element {
  const [filter, setFilter] = useState<SemesterFilter>("all"); const [sessions, setSessions] = useState<SeatingHistoryRow[]>([]); const [experience, setExperience] = useState<StudentExperienceRow[]>([]); const [students, setStudents] = useState<import("../../domain/models").Student[]>([]); const [desks, setDesks] = useState<import("../../domain/classroom-layout").LayoutItem[]>([]); const [classroomLayoutId, setClassroomLayoutId] = useState(""); const [refreshKey, setRefreshKey] = useState(0);
  useEffect(() => { const semester = filter === "all" ? undefined : filter; void Promise.all([window.appApi.history.list(schoolYearId, semester), window.appApi.history.experience(schoolYearId, semester), window.appApi.students.list(schoolYearId), window.appApi.classroom.get(schoolYearId)]).then(([history, stats, studentRows, layout]) => { setSessions(history); setExperience(stats); setStudents(studentRows); setDesks((layout?.items ?? []).filter((item) => item.type === "desk")); setClassroomLayoutId(layout?.classroomLayoutId ?? ""); }); }, [schoolYearId, filter, refreshKey]);
  const open = (sessionId: string): void => { void window.appApi.history.assignments(sessionId).then(onOpenChart); };
  return <main className="app-shell"><header className="topbar"><div><button type="button" className="back-button" onClick={onBack}>← 대시보드</button><h1>자리 기록</h1></div><div className="year-badge">확정 이력 {sessions.length}건</div></header><section className="history-section"><div className="section-heading"><h2>자리변경 이력</h2><label>조회 학기 <select value={filter} onChange={(event) => setFilter(event.target.value === "all" ? "all" : Number(event.target.value) as 1 | 2)}><option value="all">전체</option><option value="1">1학기</option><option value="2">2학기</option></select></label></div>{sessions.length ? <div className="history-list">{sessions.map((session) => <div className="history-row" key={session.seatingSessionId}><strong>{session.occurredOn} 자리배치</strong><span>{session.semester}학기</span><span>{session.assignmentCount}명</span><span>{session.note || "메모 없음"}</span><button type="button" className="text-button" onClick={() => open(session.seatingSessionId)}>자리표 열기</button></div>)}</div> : <p className="muted">선택한 학기의 자리 기록이 없습니다.</p>}</section><section className="history-section"><h2>학생별 자리 경험</h2>{experience.length ? <div className="experience-table"><div className="experience-row experience-head"><span>학생</span><span>앞</span><span>중간</span><span>뒤</span><span>왼쪽</span><span>가운데</span><span>오른쪽</span></div>{experience.map((row) => <div className="experience-row" key={row.studentId}><span>{row.name}</span><span>{row.front}</span><span>{row.middle}</span><span>{row.back}</span><span>{row.left}</span><span>{row.center}</span><span>{row.right}</span></div>)}</div> : <p className="muted">선택한 학기의 경험 통계가 없습니다.</p>}</section><HistoricalImportPreview schoolYearId={schoolYearId} classroomLayoutId={classroomLayoutId} students={students} desks={desks} onSaved={() => setRefreshKey((key) => key + 1)} /></main>;
}
