import type { CafeteriaRepository, CafeteriaHistoryRow } from "../../application/cafeteria-service";
import type { CafeteriaAssignment } from "../../domain/cafeteria-engine";
interface Statement { get(...params: unknown[]): Record<string, unknown> | undefined; all(...params: unknown[]): Record<string, unknown>[]; run(...params: unknown[]): void; }
interface SqliteDatabase { prepare(sql: string): Statement; exec(sql: string): void; }
export class SqliteCafeteriaRepository implements CafeteriaRepository {
  constructor(private readonly database: SqliteDatabase) {}
  nextSequence(schoolYearId: string, semester: number): number { const row = this.database.prepare("SELECT COALESCE(MAX(sequence_no), 0) AS max_sequence FROM cafeteria_session WHERE school_year_id = ? AND semester = ? AND status = 'confirmed'").get(schoolYearId, semester); return Number(row?.max_sequence ?? 0) + 1; }
  save(schoolYearId: string, semester: number, sequenceNo: number, assignments: CafeteriaAssignment[]): void { const sessionId = crypto.randomUUID(); const now = new Date().toISOString(); this.database.exec("BEGIN"); try { this.database.prepare("INSERT INTO cafeteria_session (cafeteria_session_id, school_year_id, semester, sequence_no, occurred_on, status, seed, created_at, confirmed_at) VALUES (?, ?, ?, ?, ?, 'confirmed', ?, ?, ?)").run(sessionId, schoolYearId, semester, sequenceNo, now.slice(0, 10), null, now, now); const insert = this.database.prepare("INSERT INTO cafeteria_assignment (assignment_id, cafeteria_session_id, student_id, queue_order, cafeteria_seat_id, role) VALUES (?, ?, ?, ?, ?, ?)"); assignments.forEach((item) => insert.run(crypto.randomUUID(), sessionId, item.studentId, item.queueOrder, item.cafeteriaSeatId, item.role ?? null)); this.database.exec("COMMIT"); } catch (error) { this.database.exec("ROLLBACK"); throw error; } }
  history(schoolYearId: string): CafeteriaHistoryRow[] { return this.database.prepare("SELECT cafeteria_session_id, semester, sequence_no, occurred_on, (SELECT COUNT(*) FROM cafeteria_assignment a WHERE a.cafeteria_session_id = s.cafeteria_session_id) AS assignment_count FROM cafeteria_session s WHERE school_year_id = ? AND status = 'confirmed' ORDER BY semester, sequence_no DESC").all(schoolYearId).map((row) => ({ sessionId: String(row.cafeteria_session_id), semester: Number(row.semester), sequenceNo: Number(row.sequence_no), occurredOn: String(row.occurred_on), assignmentCount: Number(row.assignment_count) })); }
  assignments(sessionId: string): CafeteriaAssignment[] { return this.database.prepare("SELECT student_id, queue_order, cafeteria_seat_id, role FROM cafeteria_assignment WHERE cafeteria_session_id = ? ORDER BY queue_order").all(sessionId).map((row) => ({ studentId: String(row.student_id), queueOrder: Number(row.queue_order), cafeteriaSeatId: String(row.cafeteria_seat_id), ...(row.role ? { role: "marshal" as const } : {}) })); }
}
