import type { SeatingHistoryRepository, SeatingHistoryRow, StudentExperienceRow } from "../../application/seating-history-service";
import type { ConfirmedSeatingSession } from "../../domain/models";
import { calculateSeatPosition, type LayoutItem } from "../../domain/classroom-layout";
interface Statement { all(...params: unknown[]): Record<string, unknown>[]; get(...params: unknown[]): Record<string, unknown> | undefined; }
interface SqliteDatabase { prepare(sql: string): Statement; }
export class SqliteSeatingHistoryRepository implements SeatingHistoryRepository {
  constructor(private readonly database: SqliteDatabase) {}
  list(schoolYearId: string, semester?: number): SeatingHistoryRow[] { const semesterClause = semester === undefined ? "" : " AND s.semester = ?"; const params = semester === undefined ? [schoolYearId] : [schoolYearId, semester]; return this.database.prepare(`SELECT s.seating_session_id, s.semester, s.sequence_no, s.occurred_on, s.note, COUNT(a.assignment_id) AS assignment_count FROM seating_session s LEFT JOIN seating_assignment a ON a.seating_session_id = s.seating_session_id WHERE s.school_year_id = ? AND s.status = 'confirmed'${semesterClause} GROUP BY s.seating_session_id ORDER BY s.occurred_on DESC, s.created_at DESC, s.sequence_no DESC`).all(...params).map((row) => ({ seatingSessionId: String(row.seating_session_id), semester: Number(row.semester), sequenceNo: Number(row.sequence_no), occurredOn: String(row.occurred_on), note: row.note ? String(row.note) : undefined, assignmentCount: Number(row.assignment_count) })); }
  experience(schoolYearId: string, semester?: number): StudentExperienceRow[] {
    const semesterClause = semester === undefined ? "" : " AND s.semester = ?"; const params = semester === undefined ? [schoolYearId] : [schoolYearId, semester];
    const rows = this.database.prepare(`SELECT a.student_id, a.seat_id, a.display_name_snapshot AS name, a.position_snapshot_json FROM seating_assignment a JOIN seating_session s ON s.seating_session_id = a.seating_session_id WHERE s.school_year_id = ? AND s.status = 'confirmed'${semesterClause} ORDER BY a.student_number_snapshot`).all(...params);
    const layoutRows = this.database.prepare("SELECT e.element_id, e.element_type, e.x, e.y, e.width, e.height, e.position_override_json FROM classroom_element e JOIN classroom_layout l ON l.classroom_layout_id = e.classroom_layout_id WHERE l.school_year_id = ?").all(schoolYearId);
    const layoutItems = layoutRows.map((row) => ({ id: String(row.element_id), type: row.element_type as LayoutItem["type"], x: Number(row.x), y: Number(row.y), width: Number(row.width), height: Number(row.height), positionOverride: row.position_override_json ? JSON.parse(String(row.position_override_json)) as LayoutItem["positionOverride"] : undefined }));
    const frontDoor = layoutItems.find((item) => item.type === "front-door"); const backDoor = layoutItems.find((item) => item.type === "back-door"); const positionBySeat = new Map(layoutItems.filter((item) => item.type === "desk").map((item) => [item.id, calculateSeatPosition(item, frontDoor, backDoor)]));
    const result = new Map<string, StudentExperienceRow>();
    for (const row of rows) { const current = result.get(String(row.student_id)) ?? { studentId: String(row.student_id), name: String(row.name), front: 0, middle: 0, back: 0, left: 0, center: 0, right: 0 }; const snapshot = JSON.parse(String(row.position_snapshot_json)) as { position?: { vertical?: string; horizontal?: string }; positionOverride?: { vertical?: string; horizontal?: string }; vertical?: string; horizontal?: string }; const fallback = positionBySeat.get(String(row.seat_id)); const vertical = snapshot.position?.vertical ?? snapshot.positionOverride?.vertical ?? snapshot.vertical ?? fallback?.vertical; const horizontal = snapshot.position?.horizontal ?? snapshot.positionOverride?.horizontal ?? snapshot.horizontal ?? fallback?.horizontal; if (vertical === "앞") current.front += 1; if (vertical === "중간") current.middle += 1; if (vertical === "뒤") current.back += 1; if (horizontal === "왼쪽") current.left += 1; if (horizontal === "가운데") current.center += 1; if (horizontal === "오른쪽") current.right += 1; result.set(current.studentId, current); }
    return [...result.values()];
  }
  confirmedSessions(schoolYearId: string): ConfirmedSeatingSession[] {
    const sessions = this.database.prepare("SELECT seating_session_id, sequence_no, occurred_on FROM seating_session WHERE school_year_id = ? AND status = 'confirmed' ORDER BY occurred_on ASC, created_at ASC, sequence_no ASC").all(schoolYearId);
    return sessions.map((session) => ({ sequenceNo: Number(session.sequence_no), occurredOn: String(session.occurred_on), assignments: this.database.prepare("SELECT student_id, seat_id FROM seating_assignment WHERE seating_session_id = ?").all(session.seating_session_id).map((row) => ({ studentId: String(row.student_id), seatId: String(row.seat_id) })) }));
  }
  assignments(sessionId: string): { studentId: string; seatId: string }[] { return this.database.prepare("SELECT student_id, seat_id FROM seating_assignment WHERE seating_session_id = ? ORDER BY student_number_snapshot").all(sessionId).map((row) => ({ studentId: String(row.student_id), seatId: String(row.seat_id) })); }
  latestAssignments(schoolYearId: string): { studentId: string; seatId: string }[] { const row = this.database.prepare("SELECT seating_session_id FROM seating_session WHERE school_year_id = ? AND status = 'confirmed' ORDER BY occurred_on DESC, created_at DESC, sequence_no DESC LIMIT 1").get(schoolYearId); return row ? this.assignments(String(row.seating_session_id)) : []; }
}
